[general]
import = ["/home/connor/.config/alacritty/themes/themes/tomorrow_night.toml"]

[font]
size = 12

[font.bold]
family = "Menlo"
style = "Bold"

[font.bold_italic]
family = "Menlo"
style = "Bold Italic"

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
family = "Menlo"
style = "Regular"
