[general]
import = ["/home/connor/.config/alacritty/themes/github-light.toml"]

[font]
size = 10

[font.bold]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
